### ISSUE TITLE
errors from /detections

### ISSUE THREAD

**Issue by vventirozos** [jveitchmichaelis/edgetpu_ros#1]
hello,
My setup is Kinetic on ubuntu xenial (arm) so as you can imagine it was a bit of a pain to set this up but i managed to get classify to work. but I get the following exception when i try to print from
detection's  /detections :

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/data/work/robot/catkin_ws/devel/lib/python2.7/dist-packages/vision_msgs/msg/_Detection2DArray.py", line 314, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 334, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 256, in check_type
    check_type(field_name+"[]", base_type, v)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 266, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 256, in check_type
    check_type(field_name+"[]", base_type, v)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 266, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 227, in check_type
    raise SerializationError('field %s must be of type bytes or an ascii string'%field_name)
genpy.message.SerializationError: field detections[].results[].id must be of type bytes or an ascii string

any idea what might be wrong ?

**Comment by vventirozos** [comment]
After further investigation, this was because Detection2D expects id to be a string, just typecasted it and everything worked
